export const events = [
  {
    id: 454,
    name: 'IKF PKB and PSBC Point Boxing Scoring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    promoter: 'AK Promotions',
    participants: 120,
    status: 'Upcoming',
  },
  {
    id: 711,
    name: 'SCF Semi-Contact MMA Technical Bouts',
    date: '2025/03/19',
    address: '4901 Moroney Hwy, Citrus, CA, USA',
    promoter: 'Glory DCF Semi-Contact',
    participants: 95,
    status: 'Live',
  },
  {
    id: 665,
    name: 'PSBC Point Boxing Sparring Circuit',
    date: '2025/03/18',
    address: 'Bishop, CA',
    promoter: 'Born to Win CDC',
    participants: 87,
    status: 'Closed',
  },
  {
    id: 687,
    name: 'Orlando IKF All Divisions PKB-PMT',
    date: '2025/03/18',
    address: 'Winter Park, FL, USA',
    promoter: 'Florida IKF PMT',
    participants: 110,
    status: 'Upcoming',
  },
  {
    id: 832,
    name: 'Battle of LA: Chapter 4: Muay Thai Forever',
    date: '2025/03/18',
    address: '930 Mateo St, Los Angeles, CA, USA',
    promoter: 'Born to Win CDC',
    participants: 130,
    status: 'Live',
  },
  {
    id: 'D09',
    name: 'PSBC Point Boxing Sparring',
    date: '2025/03/18',
    address: 'Newport Beach, CA, USA',
    promoter: 'Born to Win CDC',
    participants: 72,
    status: 'Closed',
  },
  {
    id: 'HCG',
    name: 'IKF PKB and PSBC Point Boxing Scoring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    promoter: 'Born to Win CDC',
    participants: 105,
    status: 'Upcoming',
  },
  {
    id: 'D09',
    name: 'IKF PKB and PSBC Point Boxing Scoring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    promoter: 'Born to Win CDC',
    participants: 98,
    status: 'Live',
  },
  {
    id: 'D09',
    name: 'IKF PKB and PSBC Point Boxing Scoring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    promoter: 'Born to Win CDC',
    participants: 83,
    status: 'Closed',
  },
  {
    id: 'D09',
    name: 'IKF PKB and PSBC Point Boxing Scoring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    promoter: 'Born to Win CDC',
    participants: 100,
    status: 'Upcoming',
  },
]

export const venues = [
  {
    id: '654',
    name: 'IKF PKB and PBSC Point Boxing Sparring',
    address: '1234 Fight St',
    city: 'Charlotte',
    state: 'NC',
    country: 'USA',
    postalCode: '28202',
    person: 'John Doe',
    email: 'john.doe@example.com',
    contact: '+1 555-1234',
    capacity: 200,
    status: 'Active',
    images: ['https://example.com/image1.jpg'],
    mapLocation: 'https://maps.google.com/?q=Charlotte,NC',
  },
  {
    id: '711',
    name: 'ISCF Semi-Contact MMA Technical Bouts',
    address: '6901 Monterey Hwy',
    city: 'Gilroy',
    state: 'CA',
    country: 'USA',
    postalCode: '95020',
    person: 'Jane Smith',
    email: 'jane.smith@example.com',
    contact: '+1 555-5678',
    capacity: 150,
    status: 'Inactive',
    images: ['https://example.com/image2.jpg'],
    mapLocation: 'https://maps.google.com/?q=Gilroy,CA',
  },
  {
    id: '665',
    name: 'PBSC Point Boxing Sparring Circuit',
    address: '456 Spar Ave',
    city: 'Bishop',
    state: 'CA',
    country: 'USA',
    postalCode: '93514',
    person: 'Mike Tyson',
    email: 'mike.tyson@example.com',
    contact: '+1 555-1122',
    capacity: 300,
    status: 'Active',
    images: ['https://example.com/image3.jpg'],
    mapLocation: 'https://maps.google.com/?q=Bishop,CA',
  },
  {
    id: '687',
    name: 'Orlando IKF All Divisions PKB/PMT',
    address: '789 Fight Lane',
    city: 'Winter Park',
    state: 'FL',
    country: 'USA',
    postalCode: '32789',
    person: 'Sarah Connor',
    email: 'sarah.connor@example.com',
    contact: '+1 555-3344',
    capacity: 250,
    status: 'Upcoming',
    images: ['https://example.com/image4.jpg'],
    mapLocation: 'https://maps.google.com/?q=Winter+Park,FL',
  },
  {
    id: '632',
    name: 'Battle of LA - Chapter 4 - Muay Thai Forever',
    address: '930 Mateo St',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    postalCode: '90021',
    person: 'Tony Jaa',
    email: 'tony.jaa@example.com',
    contact: '+1 555-5566',
    capacity: 400,
    status: 'Cancelled',
    images: ['https://example.com/image5.jpg'],
    mapLocation: 'https://maps.google.com/?q=Los+Angeles,CA',
  },
  {
    id: 'DC9A',
    name: 'PBSC Point Boxing Sparring Showcase',
    address: '22 Beachside Blvd',
    city: 'Newport Beach',
    state: 'CA',
    country: 'USA',
    postalCode: '92660',
    person: 'Amanda Lee',
    email: 'amanda.lee@example.com',
    contact: '+1 555-6655',
    capacity: 180,
    status: 'Active',
    images: ['https://example.com/image6.jpg'],
    mapLocation: 'https://maps.google.com/?q=Newport+Beach,CA',
  },
  {
    id: 'HCD1',
    name: 'Charlotte PKB Kickboxing Invitational',
    address: '77 Championship Way',
    city: 'Charlotte',
    state: 'NC',
    country: 'USA',
    postalCode: '28203',
    person: 'Bruce Lee',
    email: 'bruce.lee@example.com',
    contact: '+1 555-7788',
    capacity: 220,
    status: 'Upcoming',
    images: ['https://example.com/image7.jpg'],
    mapLocation: 'https://maps.google.com/?q=Charlotte,NC',
  },
  {
    id: 'DC9B',
    name: 'Point Boxing Rising Stars',
    address: '100 Training Dr',
    city: 'Charlotte',
    state: 'NC',
    country: 'USA',
    postalCode: '28204',
    person: 'Chuck Norris',
    email: 'chuck.norris@example.com',
    contact: '+1 555-8899',
    capacity: 160,
    status: 'Inactive',
    images: ['https://example.com/image8.jpg'],
    mapLocation: 'https://maps.google.com/?q=Charlotte,NC',
  },
  {
    id: 'DC9C',
    name: 'Youth Point Boxing Championship',
    address: '55 Youth Arena Blvd',
    city: 'Charlotte',
    state: 'NC',
    country: 'USA',
    postalCode: '28205',
    person: 'Rocky Balboa',
    email: 'rocky.b@example.com',
    contact: '+1 555-9000',
    capacity: 280,
    status: 'Active',
    images: ['https://example.com/image9.jpg'],
    mapLocation: 'https://maps.google.com/?q=Charlotte,NC',
  },
  {
    id: 'DC9D',
    name: 'All-State PKB and PMT Showcase',
    address: '888 Competition Lane',
    city: 'Charlotte',
    state: 'NC',
    country: 'USA',
    postalCode: '28206',
    person: 'Ivan Drago',
    email: 'ivan.drago@example.com',
    contact: '+1 555-1010',
    capacity: 350,
    status: 'Upcoming',
    images: ['https://example.com/image10.jpg'],
    mapLocation: 'https://maps.google.com/?q=Charlotte,NC',
  },
]

export const brackets = [
  {
    id: 1,
    title: "Men's Novice 100.1LBS - 110.0LBS",
    subtitle: 'Point Sparring - International Rules',
    status: 'Open',
    startDayNumber: '1',
    group: '',
    ringNumber: '',
    bracketSequence: '',
    boutRound: '1',
    maxCompetitors: '1',
    images: [
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
      {
        src: '/anthony.png',
        alt: 'fighter',
        name: 'Anthony Bui',
        age: '36yrs',
      },
      {
        src: '/davison.png',
        alt: 'fighter',
        name: 'Chainsaw Davison',
        age: '36yrs',
      },
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
    ],
  },
  {
    id: 2,
    title: "Boys' Novice 70.1LBS - 80.0LBS",
    subtitle: 'Continuous Sparring - Regional Rules',
    status: 'Started',
    startDayNumber: '2',
    group: '',
    ringNumber: '',
    bracketSequence: '',
    boutRound: '2',
    maxCompetitors: '3',
    images: [
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
      {
        src: '/anthony.png',
        alt: 'fighter',
        name: 'Anthony Bui',
        age: '36yrs',
      },
      {
        src: '/davison.png',
        alt: 'fighter',
        name: 'Chainsaw Davison',
        age: '36yrs',
      },
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
    ],
  },
  {
    id: 3,
    title: "Boys' Novice 120.1LBS - 130.0LBS",
    subtitle: 'Point Sparring - International Rules',
    status: 'Open',
    startDayNumber: '1',
    group: '',
    ringNumber: '',
    bracketSequence: '',
    boutRound: '4',
    maxCompetitors: '3',
    images: [
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
      {
        src: '/anthony.png',
        alt: 'fighter',
        name: 'Anthony Bui',
        age: '36yrs',
      },
      {
        src: '/davison.png',
        alt: 'fighter',
        name: 'Chainsaw Davison',
        age: '36yrs',
      },
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
    ],
  },
]

export const boutsAndResults = [
  {
    id: 1,
    fighters1: { src: '/fighter.png', name: 'Eric Franks', age: 36 },
    fighter2: {
      src: '/davison.png',
      name: 'Chainsaw Davison',
      age: 36,
    },
    roundNumber: 1,
  },
  // {
  //   id: 2,
  //   fighters1: { src: '/anthony.png', name: 'Anthony Bui', age: 36 },
  //   fighter2: {
  //     src: '/fighter.png',
  //     name: 'Eric Franks',
  //     age: 36,
  //   },
  //   roundNumber: 1,
  // },
  {
    id: 2,
    fighters1: { src: '/anthony.png', name: 'Anthony Bui', age: 36 },
    fighter2: {
      src: '/fighter.png',
      name: 'Eric Franks',
      age: 36,
    },
    roundNumber: 2,
  },
]

export const cashPaymentAndCodesEvents = [
  {
    id: 1,
    name: 'IKF Point Muay Thai and PBSC Point Boxing Sparring Seminar by Anthony Bui- Mexico (03/22/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: false,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: false,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: false,
      },
    ],
  },
  {
    id: 2,
    name: 'ISCF Semi-Contact MMA Technical Bouts (03/29/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: false,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: false,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: false,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  {
    id: 3,
    name: 'PBSC Point Boxing Sparring Circuit - Bishop, CA (03/29/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: false,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  {
    id: 4,
    name: 'PBSC Point Boxing Sparring Circuit - Newport Beach 2025 (04/05/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  { id: 5, name: 'Orlando IKF ALL DIVISIONS PKB/PMT (03/30/2025)' },
  {
    id: 6,
    name: 'IKF PKB and PBSC Point Boxing Sparring,Charlotte, NC (03/29/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  {
    id: 7,
    name: 'PBSC Point Boxing Sparring Circuit - EVO Sport Expo 2025 (04/12/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  {
    id: 8,
    name: 'PBSC Point Boxing Sparring Circuit - EVO Sport Expo 2025 (04/12/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  {
    id: 9,
    name: 'PBSC Point Boxing Sparring Circuit - EVO Sport Expo 2025 (04/12/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  {
    id: 10,
    name: 'IKF Semi-Contact Kickboxing & Muay Thai (04/13/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  {
    id: 11,
    name: 'Fusion IKF Point Sparring Tournament (04/26/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  {
    id: 12,
    name: 'IKF Point Muay Thai / Kickboxing And PBSC Point Boxing Sparring -Moncks, Corner- Sunday! (04/13/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  {
    id: 13,
    name: 'IKF PKB and PBSC Point Boxing Sparring,Charlotte, NC (03/29/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
  {
    id: 14,
    name: 'PBSC Point Boxing Sparring Circuit - EVO Sport Expo 2025 (04/12/2025)',
    users: [
      {
        id: 101,
        name: 'Eric Franks',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'Io0',
        amount: '$36',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 102,
        name: 'Sophie Moore',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'E21',
        amount: '$32',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 103,
        name: 'Matt Cannon',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'H2J',
        amount: '$34',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 104,
        name: 'Graham Hills',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: '0FP',
        amount: '$16',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 105,
        name: 'Sandy Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'KKW',
        amount: '$18',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 106,
        name: 'Andy Smith',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$12',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 107,
        name: 'Lily Woods',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'HC0',
        amount: '$40',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 108,
        name: 'Patrick Meyer',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$22',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 109,
        name: 'Francis Wilton',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$20',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
      {
        id: 110,
        name: 'Ernest Houston',
        profilePic: '/john.png',
        email: 'eric@gmail.com',
        code: 'DG9',
        amount: '$24',
        date: '2025/03/18 15:00:19',
        notes: 'Credited from previous event',
        redeemed: true,
      },
    ],
  },
]

export const rankings = [
  {
    rank: 1,
    fighterName: 'John Doe',
    age: 28,
    gender: 'Male',
    result: '10 / 2 / 1',
    country: 'USA',
    team: 'Alpha MMA',
    email: 'john@example.com',
    contact: '+1 555-1234',
    capacity: 500,
    status: 'Approved',
    images: ['/img/john1.jpg', '/img/john2.jpg'],
    mapLocation: 'https://maps.google.com/?q=New+York',
  },
  {
    rank: 2,
    fighterName: 'Lisa Chang',
    age: 24,
    gender: 'Female',
    result: '8 / 1 / 0',
    country: 'Canada',
    team: 'Red Dragon',
    email: 'lisa@example.com',
    contact: '+1 555-2234',
    capacity: 450,
    status: 'Pending',
    images: ['/img/lisa1.jpg'],
    mapLocation: 'https://maps.google.com/?q=Toronto',
  },
  {
    rank: 3,
    fighterName: 'Carlos Méndez',
    age: 31,
    gender: 'Male',
    result: '15 / 5 / 3',
    country: 'Mexico',
    team: 'Titan Gym',
    email: 'carlos@example.com',
    contact: '+52 555-3344',
    capacity: 300,
    status: 'Approved',
    images: [],
    mapLocation: 'https://maps.google.com/?q=Mexico+City',
  },
  {
    rank: 4,
    fighterName: 'Amara Njeri',
    age: 26,
    gender: 'Female',
    result: '12 / 4 / 2',
    country: 'Kenya',
    team: 'Savage Squad',
    email: 'amara@example.com',
    contact: '+254 700-123456',
    capacity: 400,
    status: 'Rejected',
    images: ['/img/amara.jpg'],
    mapLocation: 'https://maps.google.com/?q=Nairobi',
  },
  {
    rank: 5,
    fighterName: 'David Kim',
    age: 29,
    gender: 'Male',
    result: '9 / 3 / 1',
    country: 'South Korea',
    team: 'Seoul Warriors',
    email: 'david@example.com',
    contact: '+82 10-1234-5678',
    capacity: 550,
    status: 'Approved',
    images: ['/img/david.jpg'],
    mapLocation: 'https://maps.google.com/?q=Seoul',
  },
  {
    rank: 6,
    fighterName: 'Emily Smith',
    age: 27,
    gender: 'Female',
    result: '11 / 2 / 2',
    country: 'UK',
    team: 'Iron Fist',
    email: 'emily@example.com',
    contact: '+44 20 7946 0958',
    capacity: 420,
    status: 'Pending',
    images: [],
    mapLocation: 'https://maps.google.com/?q=London',
  },
  {
    rank: 7,
    fighterName: 'Ravi Singh',
    age: 30,
    gender: 'Male',
    result: '14 / 4 / 0',
    country: 'India',
    team: 'Delhi Knockouts',
    email: 'ravi@example.com',
    contact: '+91 98765 43210',
    capacity: 600,
    status: 'Approved',
    images: ['/img/ravi.jpg'],
    mapLocation: 'https://maps.google.com/?q=Delhi',
  },
  {
    rank: 8,
    fighterName: 'Nora Petrovic',
    age: 25,
    gender: 'Female',
    result: '7 / 1 / 0',
    country: 'Croatia',
    team: 'Zagreb Lions',
    email: 'nora@example.com',
    contact: '+385 91 123 4567',
    capacity: 350,
    status: 'Pending',
    images: [],
    mapLocation: 'https://maps.google.com/?q=Zagreb',
  },
  {
    rank: 9,
    fighterName: 'Takeshi Yamamoto',
    age: 32,
    gender: 'Male',
    result: '13 / 6 / 2',
    country: 'Japan',
    team: 'Kyoto Blades',
    email: 'takeshi@example.com',
    contact: '+81 70 1234 5678',
    capacity: 480,
    status: 'Approved',
    images: ['/img/takeshi.jpg'],
    mapLocation: 'https://maps.google.com/?q=Kyoto',
  },
  {
    rank: 10,
    fighterName: 'Fatima Zahra',
    age: 23,
    gender: 'Female',
    result: '6 / 0 / 1',
    country: 'Morocco',
    team: 'Casablanca Warriors',
    email: 'fatima@example.com',
    contact: '+212 600-123456',
    capacity: 390,
    status: 'Approved',
    images: ['/img/fatima.jpg'],
    mapLocation: 'https://maps.google.com/?q=Casablanca',
  },
]

export const suspensionsData = [
  {
    id: 'SUS-001',
    status: 'Active',
    type: 'Disciplinary',
    occurred: '2024-01-15',
    okToTrain: '2024-06-15',
    okToCompete: '2024-08-15',
    indefinite: false,
    person: 'John Anderson',
  },
  {
    id: 'SUS-002',
    status: 'Active',
    type: 'Medical',
    occurred: '2024-02-22',
    okToTrain: '2024-05-22',
    okToCompete: '2024-07-22',
    indefinite: false,
    person: 'Maria Rodriguez',
  },
  {
    id: 'SUS-003',
    status: 'Inactive',
    type: 'Disciplinary',
    occurred: '2023-11-08',
    okToTrain: '2024-02-08',
    okToCompete: '2024-03-08',
    indefinite: false,
    person: 'David Chen',
  },
  {
    id: 'SUS-004',
    status: 'Active',
    type: 'Disciplinary',
    occurred: '2024-03-10',
    okToTrain: null,
    okToCompete: null,
    indefinite: true,
    person: 'Sarah Thompson',
  },
  {
    id: 'SUS-005',
    status: 'Active',
    type: 'Medical',
    occurred: '2024-01-30',
    okToTrain: '2024-04-30',
    okToCompete: '2024-06-30',
    indefinite: false,
    person: "Michael O'Connor",
  },
  {
    id: 'SUS-006',
    status: 'Inactive',
    type: 'Medical',
    occurred: '2023-09-15',
    okToTrain: '2023-12-15',
    okToCompete: '2024-01-15',
    indefinite: false,
    person: 'Jennifer Lee',
  },
  {
    id: 'SUS-007',
    status: 'Active',
    type: 'Disciplinary',
    occurred: '2024-02-05',
    okToTrain: '2024-08-05',
    okToCompete: '2024-10-05',
    indefinite: false,
    person: 'Robert Williams',
  },
  {
    id: 'SUS-008',
    status: 'Active',
    type: 'Medical',
    occurred: '2024-03-20',
    okToTrain: '2024-09-20',
    okToCompete: '2024-11-20',
    indefinite: false,
    person: 'Emily Davis',
  },
  {
    id: 'SUS-009',
    status: 'Inactive',
    type: 'Disciplinary',
    occurred: '2023-08-12',
    okToTrain: '2023-11-12',
    okToCompete: '2023-12-12',
    indefinite: false,
    person: 'James Wilson',
  },
  {
    id: 'SUS-010',
    status: 'Active',
    type: 'Medical',
    occurred: '2024-01-08',
    okToTrain: '2024-07-08',
    okToCompete: '2024-09-08',
    indefinite: false,
    person: 'Lisa Garcia',
  },
  {
    id: 'SUS-011',
    status: 'Active',
    type: 'Disciplinary',
    occurred: '2024-04-01',
    okToTrain: null,
    okToCompete: null,
    indefinite: true,
    person: 'Thomas Brown',
  },
  {
    id: 'SUS-012',
    status: 'Inactive',
    type: 'Medical',
    occurred: '2023-07-25',
    okToTrain: '2023-10-25',
    okToCompete: '2023-11-25',
    indefinite: false,
    person: 'Ashley Martinez',
  },
  {
    id: 'SUS-013',
    status: 'Active',
    type: 'Disciplinary',
    occurred: '2024-02-14',
    okToTrain: '2024-05-14',
    okToCompete: '2024-07-14',
    indefinite: false,
    person: 'Christopher Taylor',
  },
  {
    id: 'SUS-014',
    status: 'Active',
    type: 'Medical',
    occurred: '2024-03-28',
    okToTrain: '2024-06-28',
    okToCompete: '2024-08-28',
    indefinite: false,
    person: 'Amanda Johnson',
  },
  {
    id: 'SUS-015',
    status: 'Inactive',
    type: 'Disciplinary',
    occurred: '2023-10-03',
    okToTrain: '2024-01-03',
    okToCompete: '2024-02-03',
    indefinite: false,
    person: 'Ryan Miller',
  },
  {
    id: 'SUS-016',
    status: 'Active',
    type: 'Medical',
    occurred: '2024-01-18',
    okToTrain: '2024-04-18',
    okToCompete: '2024-06-18',
    indefinite: false,
    person: 'Nicole White',
  },
  {
    id: 'SUS-017',
    status: 'Active',
    type: 'Disciplinary',
    occurred: '2024-03-05',
    okToTrain: '2024-09-05',
    okToCompete: '2024-11-05',
    indefinite: false,
    person: 'Kevin Harris',
  },
  {
    id: 'SUS-018',
    status: 'Inactive',
    type: 'Medical',
    occurred: '2023-06-10',
    okToTrain: '2023-09-10',
    okToCompete: '2023-10-10',
    indefinite: false,
    person: 'Stephanie Clark',
  },
  {
    id: 'SUS-019',
    status: 'Active',
    type: 'Disciplinary',
    occurred: '2024-04-12',
    okToTrain: null,
    okToCompete: null,
    indefinite: true,
    person: 'Daniel Lewis',
  },
  {
    id: 'SUS-020',
    status: 'Active',
    type: 'Medical',
    occurred: '2024-02-28',
    okToTrain: '2024-05-28',
    okToCompete: '2024-07-28',
    indefinite: false,
    person: 'Rachel Walker',
  },
]

export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL

export const roles = {
  admin: 'Admin',
  user: 'User',
  fighter: 'Fighter',
}

export const apiConstants = {
  create: 201,
  success: 200,
}
