export const events = [
  {
    id: 454,
    name: 'IKF PKB and PSBC Point Boxing Scoring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    promoter: 'AK Promotions',
  },
  {
    id: 711,
    name: 'SCF Semi-Contact MMA Technical Bouts',
    date: '2025/03/19',
    address: '4901 Moroney Hwy, Citrus, CA, USA',
    promoter: 'Glory DCF Semi-Contact',
  },
  {
    id: 665,
    name: 'PSBC Point Boxing Sparring Circuit',
    date: '2025/03/18',
    address: 'Bishop, CA',
    promoter: 'Born to Win CDC',
  },
  {
    id: 687,
    name: 'Orlando IKF All Divisions PKB-PMT',
    date: '2025/03/18',
    address: 'Winter Park, FL, USA',
    promoter: 'Florida IKF PMT',
  },
  {
    id: 832,
    name: 'Battle of LA: Chapter 4: Muay Thai Forever',
    date: '2025/03/18',
    address: '930 Mateo St, Los Angeles, CA, USA',
    promoter: 'Born to Win CDC',
  },
  {
    id: 'D09',
    name: 'PSBC Point Boxing Sparring',
    date: '2025/03/18',
    address: 'Newport Beach, CA, USA',
    promoter: 'Born to Win CDC',
  },
  {
    id: 'HCG',
    name: 'IKF PKB and PSBC Point Boxing Scoring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    promoter: 'Born to Win CDC',
  },
  {
    id: 'D09',
    name: 'IKF PKB and PSBC Point Boxing Scoring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    promoter: 'Born to Win CDC',
  },
  {
    id: 'D09',
    name: 'IKF PKB and PSBC Point Boxing Scoring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    promoter: 'Born to Win CDC',
  },
  {
    id: 'D09',
    name: 'IKF PKB and PSBC Point Boxing Scoring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    promoter: 'Born to Win CDC',
  },
]

export const venues = [
  {
    id: '654',
    name: 'IKF PKB and PBSC Point Boxing Sparring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    url: 'https://admin.lkfflightpbj',
  },
  {
    id: '711',
    name: 'ISCF Semi-Contact MMA Technical Bouts',
    date: '2025/03/18',
    address: '6901 Monterey Hwy, Gilroy, CA, USA',
    url: '',
  },
  {
    id: '665',
    name: 'PBSC Point Boxing Sparring Circuit',
    date: '2025/03/18',
    address: 'Bishop, CA',
    url: 'https://admin.lkfflightpbj',
  },
  {
    id: '687',
    name: 'Orlando IKF All Divisions PKB/PMT',
    date: '2025/03/18',
    address: 'Winter Park, FL, USA',
    url: '',
  },
  {
    id: '632',
    name: 'Battle of LA- Chapter 4- Muay Thai Forever',
    date: '2025/03/18',
    address: '930 Mateo St, Los Angeles, CA, USA',
    url: '',
  },
  {
    id: 'DC9',
    name: 'PBSC Point Boxing Sparring',
    date: '2025/03/18',
    address: 'Newport Beach, CA, USA',
    url: '',
  },
  {
    id: 'HCD',
    name: 'IKF PKB and PBSC Point Boxing Sparring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    url: '',
  },
  {
    id: 'DC9',
    name: 'IKF PKB and PBSC Point Boxing Sparring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    url: '',
  },
  {
    id: 'DC9',
    name: 'IKF PKB and PBSC Point Boxing Sparring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    url: '',
  },
  {
    id: 'DC9',
    name: 'IKF PKB and PBSC Point Boxing Sparring',
    date: '2025/03/18',
    address: 'Charlotte, NC',
    url: '',
  },
]

export const brackets = [
  {
    id: 1,
    title: "Men's Novice 100.1LBS - 110.0LBS",
    subtitle: 'Point Sparring - International Rules',
    status: 'Open',
    startDayNumber: '1',
    group: '',
    ringNumber: '',
    bracketSequence: '',
    boutRound: '1',
    maxCompetitors: '1',
    images: [
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
      {
        src: '/anthony.png',
        alt: 'fighter',
        name: 'Anthony Bui',
        age: '36yrs',
      },
      {
        src: '/davison.png',
        alt: 'fighter',
        name: 'Chainsaw Davison',
        age: '36yrs',
      },
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
    ],
  },
  {
    id: 2,
    title: "Boys' Novice 70.1LBS - 80.0LBS",
    subtitle: 'Continuous Sparring - Regional Rules',
    status: 'Started',
    startDayNumber: '2',
    group: '',
    ringNumber: '',
    bracketSequence: '',
    boutRound: '2',
    maxCompetitors: '3',
    images: [
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
      {
        src: '/anthony.png',
        alt: 'fighter',
        name: 'Anthony Bui',
        age: '36yrs',
      },
      {
        src: '/davison.png',
        alt: 'fighter',
        name: 'Chainsaw Davison',
        age: '36yrs',
      },
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
    ],
  },
  {
    id: 3,
    title: "Boys' Novice 120.1LBS - 130.0LBS",
    subtitle: 'Point Sparring - International Rules',
    status: 'Open',
    startDayNumber: '1',
    group: '',
    ringNumber: '',
    bracketSequence: '',
    boutRound: '4',
    maxCompetitors: '3',
    images: [
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
      {
        src: '/anthony.png',
        alt: 'fighter',
        name: 'Anthony Bui',
        age: '36yrs',
      },
      {
        src: '/davison.png',
        alt: 'fighter',
        name: 'Chainsaw Davison',
        age: '36yrs',
      },
      {
        src: '/fighter.png',
        alt: 'fighter',
        name: 'Eric Franks',
        age: '36yrs',
      },
    ],
  },
]

export const boutsAndResults = [
  {
    id: 1,
    fighters1: { src: '/fighter.png', name: 'Eric Franks', age: 36 },
    fighter2: {
      src: '/davison.png',
      name: 'Chainsaw Davison',
      age: 36,
    },
    roundNumber: 1,
  },
  // {
  //   id: 2,
  //   fighters1: { src: '/anthony.png', name: 'Anthony Bui', age: 36 },
  //   fighter2: {
  //     src: '/fighter.png',
  //     name: 'Eric Franks',
  //     age: 36,
  //   },
  //   roundNumber: 1,
  // },
  {
    id: 2,
    fighters1: { src: '/anthony.png', name: 'Anthony Bui', age: 36 },
    fighter2: {
      src: '/fighter.png',
      name: 'Eric Franks',
      age: 36,
    },
    roundNumber: 2,
  },
]
