import { Saira_Condensed } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import SnackbarProviderClient from './components/SnackbarProviderClient'

const saira = Saira_Condensed({
  variable: '--font-saira-condensed',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${saira.variable} antialiased`}>
        <SnackbarProviderClient>
          <Navbar />
          {children}
          <Footer />
        </SnackbarProviderClient>
      </body>
    </html>
  )
}
